### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by chun-awa** [LingmoOS/logo#1]
@lingmo-dream @Sato-Ida
e.g.
- CC0-1.0
- CC-BY-4.0
- CC-BY-NC-4.0
- CC-BY-NC-SA-4.0(recommended)
- CC-BY-NC-ND-4.0

See <https://creativecommons.org/> for more information

**Comment by Sato-Ida** [comment]
The last choice (CC-BY-NC-ND-4.0),please
